# Generated by Django 5.0.3 on 2024-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='account',
            new_name='accounts',
        ),
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='05817765541e4774ae504a87b29c7586', editable=False, max_length=255),
        ),
    ]
